version: "3.8"

services:
  db:
    container_name: database
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_USER=pos
      - POSTGRES_PASSWORD=lahiru12
      - POSTGRES_DB=pos
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  demo-svc:
      container_name: demo-svc
      build: .
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/pos
        SPRING_DATASOURCE_USERNAME: pos
        SPRING_DATASOURCE_PASSWORD: lahiru12
        SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        SPRING_JPA_SHOW_SQL: true
        SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      depends_on:
        - db
volumes:
    postgres-data: